name: wordsmith_utils
description: Utility code meant to be used with the desktop and mobile application of Wordsmith.
publish_to: none

version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.0.0
  file_selector: ^1.0.1
  mime: ^1.0.4
  logging: ^1.2.0
  intl: ^0.18.1
  http_parser: ^4.0.2
  provider: ^6.0.5

# Temporary override due to flutter_secure_storage breaking Linux support
dependency_overrides:
  flutter_secure_storage_linux:
    git:
      url: https://github.com/prateekmedia/flutter_secure_storage.git
      ref: patch-1
      path: flutter_secure_storage_linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
