name: wordsmith_mobile
description: "Mobile client for the Wordsmith ebook application"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.3
  logging: ^1.2.0
  adaptive_theme: ^3.6.0
  carousel_slider: ^4.2.1
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2
  sqflite: ^2.3.3
  currency_text_input_formatter: ^2.1.14
  font_awesome_flutter: ^10.7.0
  webview_flutter: ^4.7.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_rating_bar: ^4.0.1
  flutter_html: ^3.0.0-beta.2

  wordsmith_utils:
    path: ../wordsmith_utils

  epub_view:
    git:
      url: https://github.com/AdivonSlav/packages.flutter
      ref: dev
      path: packages/epub_view/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile_image_placeholder.jpeg
    - assets/images/no_image_placeholder.png
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
